--
-- Criado por Ricardo Cuevas
-- email: rbc.works@gmail.com
-- https://www.facebook.com/rrrrbc
--
CREATE TABLE IF NOT EXISTS `Curso` (
  `CursoID` int(11) NOT NULL AUTO_INCREMENT,
  `Nome` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`CursoID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=221 ;


INSERT INTO `Curso` (`CursoID`,  `Nome`) VALUES
(1,  'Administração'),
(2,  'Agrimensura'),
(3,  'Agroecologia'),
(4,  'Agroindústria'),
(5,  'Agronomia(ou Engenharia agronômica)'),
(6,  'Análise e Desenvolvimento de Sistemas'),
(7,  'Antropologia'),
(8,  'Aquacultura'),
(9,  'Arqueologia'),
(10,  'Arquitectura'),
(11,  'Arquivística'),
(12,  'Artes Cênicas'),
(13,  'Artes Visuais'),
(14,  'Astronomia'),
(15,  'Automação Industrial'),
(16,  'Biblioteconomia'),
(17,  'Biocombustíveis'),
(18,  'Bioengenharia'),
(19,  'Biofísica'),
(20,  'Biologia marinha'),
(21,  'Biologia(licenciatura)'),
(22,  'Biomedicina'),
(23,  'Biotecnologia'),
(24,  'Botânica'),
(25,  'Cafeicultura'),
(26,  'Ciência & Tecnologia'),
(27,  'Ciência da Computação'),
(28,  'Ciência dos Alimentos'),
(29,  'Ciência dos materiais'),
(30,  'Ciência Política(ou Ciências do Estado)'),
(31,  'Ciências Aeronáuticas'),
(32,  'Ciências Agrárias(licenciatura)'),
(33,  'Ciências Ambientais'),
(34,  'Ciências Atuariais'),
(35,  'Ciências Biológicas'),
(36,  'Ciências Biomoleculares'),
(37,  'Ciências da Saúde'),
(38,  'Ciências do Meio Aquático'),
(39,  'Ciências Humanas(licenciatura)'),
(40,  'Ciências Matemáticas da Terra'),
(41,  'Ciências Naturais(licenciatura)'),
(42,  'Ciências SociaisLicenciatura'),
(43,  'Cinema'),
(44,  'Comércio Exterior'),
(45,  'Comunicação social'),
(46,  'Construção de Edifícios'),
(47,  'Construção de Estradas'),
(48,  'Construção Naval'),
(49,  'Contabilidade'),
(50,  'Cooperativismo'),
(51,  'Cosmetologia'),
(52,  'Dança(licenciatura)'),
(53,  'Defesa e Gestão Estratégica Internacional'),
(54,  'Desenho Industrial'),
(55,  'Design de Interiores'),
(56,  'Design de Jogos Digitais'),
(57,  'Design de Moda'),
(58,  'Design de produto'),
(59,  'Design gráfico'),
(60,  'Direito'),
(61,  'Drenagem e Irrigação'),
(62,  'Ecologia'),
(63,  'Economia'),
(64,  'Economia Doméstica'),
(65,  'Editoração'),
(66,  'Educação Artística(licenciatura)'),
(67,  'Educação do Campo(licenciatura)'),
(68,  'Educação física(licenciatura)'),
(69,  'Energias Renováveis'),
(70,  'Enfermagem'),
(71,  'Engenharia aeroespacial'),
(72,  'Engenharia aeronáutica'),
(73,  'Engenharia Agrícola'),
(74,  'Engenharia Ambiental'),
(75,  'Engenharia biomédica'),
(76,  'Engenharia Cartográfica(ou Engenharia geográfica)'),
(77,  'Engenharia Civil'),
(78,  'Engenharia de Alimentos'),
(79,  'Engenharia de Computação'),
(80,  'Engenharia de controle e automação'),
(81,  'Engenharia de manufatura'),
(82,  'Engenharia de Materiais'),
(83,  'Engenharia de Minas'),
(84,  'Engenharia de Pesca'),
(85,  'Engenharia de Petróleo'),
(86,  'Engenharia de Produção'),
(87,  'Engenharia de Sistemas Eletrônicos'),
(88,  'Engenharia de Software'),
(89,  'Engenharia de Tecidos'),
(90,  'Engenharia de Telecomunicações'),
(91,  'Engenharia Elétrica(ou engenharia de energia)'),
(92,  'Engenharia Física'),
(93,  'Engenharia Florestal'),
(94,  'Engenharia geológica'),
(95,  'Engenharia Industrial Madeireira'),
(96,  'Engenharia Mecânica'),
(97,  'Engenharia Mecatrônica'),
(98,  'Engenharia Metalúrgica'),
(99,  'Engenharia Militar'),
(100,  'Engenharia Naval e Oceânica'),
(101,  'Engenharia Nuclear'),
(102,  'Engenharia Química'),
(103,  'Engenharia Sanitária'),
(104,  'Engenharia Têxtil'),
(105,  'Enologia'),
(106,  'Escultura'),
(107,  'Esporte e Lazer'),
(108,  'Estatística'),
(109,  'Eventos'),
(110,  'Farmácia(ou Bioquímica)'),
(111,  'Filosofia(licenciatura)'),
(112,  'Física computacional'),
(113,  'Física médica'),
(114,  'Física(licenciatura)'),
(115,  'Fisioterapia'),
(116,  'Fonoaudiologia'),
(117,  'Fotografia'),
(118,  'Fruticultura'),
(119,  'Gastronomia'),
(120,  'Geofísica'),
(121,  'Geografia(licenciatura)'),
(122,  'Geologia(licenciatura)'),
(123,  'Geoprocessamento e Sensoreamento Remoto'),
(124,  'Gerontologia'),
(125,  'Gestão Ambiental'),
(126,  'Gestão Comercial'),
(127,  'Gestão da Qualidade'),
(128,  'Gestão da Tecnologia da Informação'),
(129,  'Gestão de Petróleo e Gás'),
(130,  'Gestão de Recursos Hídricos'),
(131,  'Gestão de Segurança Privada'),
(132,  'Gestão do Agronegócio'),
(133,  'Gestão Financeira'),
(134,  'Gestão Hospitalar'),
(135,  'Gestão Portuária'),
(136,  'Gestão Pública'),
(137,  'Gravurismo'),
(138,  'História da Arte'),
(139,  'História(licenciatura)'),
(140,  'Horticultura'),
(141,  'Hotelaria'),
(142,  'Informática biomédica'),
(143,  'Informática(licenciatura)'),
(144,  'Jornalismo'),
(145,  'Letras(licenciatura)'),
(146,  'Linguística'),
(147,  'Logística'),
(148,  'Manutenção Industrial'),
(149,  'Matemática Aplicada'),
(150,  'Matemática computacional'),
(151,  'Matemática(licenciatura)'),
(152,  'Mecatrônica e Mecânica de Precisão'),
(153,  'Medicina'),
(154,  'Medicina veterinária'),
(155,  'Meliponicultura'),
(156,  'Mercadologia'),
(157,  'Meteorologia'),
(158,  'Microbiologiae Imunologia'),
(159,  'Mineração'),
(160,  'Museologia'),
(161,  'Música(licenciatura)'),
(162,  'Nanotecnologia'),
(163,  'Naturologia'),
(164,  'Negócios Imobiliários'),
(165,  'Neurociência'),
(166,  'Nutrição'),
(167,  'Obstetrícia'),
(168,  'Oceanografia(arcaicamente referido como Ciência dos Mares)'),
(169,  'Odontologia'),
(170,  'Oftálmica'),
(171,  'Ordenamento do Território'),
(172,  'Paisagismo'),
(173,  'Pedagogia(licenciatura)'),
(174,  'Pintura'),
(175,  'Processamento de Dados'),
(176,  'Processos Escolares'),
(177,  'Processos Metalúrgicos'),
(178,  'Produção Audiovisual(popularmente referido como Rádio & TV, e mais arcaicamente comoRadialismo)'),
(179,  'Produção Cultural'),
(180,  'Produção de Aguardente'),
(181,  'Produção de Laticínios'),
(182,  'Produção de Materiais Plásticos'),
(183,  'Produção Fonográfica'),
(184,  'Produção Sucroalcooeira'),
(185,  'Produção Têxtil'),
(186,  'Psicologia'),
(187,  'Publicidade & Propaganda'),
(188,  'Química ambiental'),
(189,  'Química industrial'),
(190,  'Química(licenciatura)'),
(191,  'Quiropraxia'),
(192,  'Radiologia'),
(193,  'Recursos Humanos'),
(194,  'Redes de Computadores'),
(195,  'Redes de Telecomunicações'),
(196,  'Relações Internacionais'),
(197,  'Relações Públicas'),
(198,  'Saneamento Ambiental'),
(199,  'Saúde Coletiva'),
(200,  'Secretariado'),
(201,  'Segurança da Informação'),
(202,  'Segurança no Trabalho'),
(203,  'Segurança Pública'),
(204,  'Serviço Social'),
(205,  'Silvicultura'),
(206,  'Sistemas Biomédicos'),
(207,  'Sistemas de Navegação Fluvial'),
(208,  'Sistemas Elétricos'),
(209,  'Sistemas Embarcados'),
(210,  'Sistemas para Internet'),
(211,  'Sociologia(licenciatura)'),
(212,  'Teatro(licenciatura)'),
(213,  'Telemática'),
(214,  'Teologia'),
(215,  'Terapia ocupacional'),
(216,  'Transporte Aéreo'),
(217,  'Transporte Terrestre'),
(218,  'Turismologia'),
(219,  'Urbanismo'),
(220,  'Zootecnia');
